apiVersion: v1
kind: ConfigMap
metadata:
  name: web-info-html
binaryData: {}
data:
  index.html: |
    <html>
      <body style="background-color: #282c34; color: white; font-family: sans-serif; text-align: center;">
        <h1>Projet K8s de Jin - Lab SRE</h1>
        <p>Etat : <span style="color: #61dafb;">Synchronis√© par ArgoCD</span></p>
        <p>Ma stack : K3d, ArgoCD, Kustomize</p>
      </body>
    </html>