apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-info
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-info
  template:
    metadata:
      labels:
        app: web-info
    spec:
      containers:
      - name: web-info
        image: nginx:alpine
        ports:
        - containerPort: 80