apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

# On personnalise pour la PROD
patches:
  - target:
      kind: Deployment
      name: web-info
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3 # On veut de la haute disponibilité en prod
  - target:
      kind: Ingress
      name: web-info-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /prod # On change le chemin pour éviter le conflit avec la Dev