apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev- # Tous tes objets s'appelleront dev-web-info au lieu de web-info

patches:
  - target:
      kind: Deployment
      name: web-info
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1 